#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$(git diff --exit-code ./prisma/schema.prisma)" = "1" ]; then
echo "Cannot change the schema in a non-db branch. Aborting commit..."
echo "Unstage schema.prisma to commit."
exit 1
fi

npm run build:css
npx lint-staged

#!/bin/sh

# full paths from the repo root separated by newlines
MUST_NOT_CHANGE='prisma'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec 1>&2

if git diff --cached --name-only $against |
   grep --quiet --line-regexp --fixed-strings "$MUST_NOT_CHANGE"
then
  echo Commit would modify one or more files that must not change.
  exit 1
else
  exit 0
fi
